DE8754 Meta Image
crdschurch/jekyll-crds pull request #50
Opened 2021-11-22 21:08 UTC by silasbaur

## Task
Fix meta image to show up on pages where a meta object is given
[Rally Story](https://rally1.rallydev.com/#/?detail=/defect/615638488679&fdp=true)

2021-11-23 14:32 UTC, tcmacdonald requested changes
@silasbaur One comment... also– don't we need to add the `meta` collection to `config.yml`?

2021-11-23 14:32 UTC, tcmacdonald commented on lib/jekyll-crds/filters/meta_filters.rb
> +      id = page['meta']['id'] if page.to_h.dig('meta', 'id').present?
Consider this logic instead of your trailing `if` statement... 

```
id = page.to_h.dig('meta', 'id')
```

2021-11-23 14:51 UTC, silasbaur commented
Here is the PR for Crds-Net: https://github.com/crdschurch/crds-net/pull/2478

2021-11-24 14:25 UTC, tcmacdonald approved these changes

2021-11-24 14:26 UTC, merged